source 'http://rubygems.org'

gem 'seimtra', '0.0.1'
gem 'sinatra'
gem 'sequel'
gem 'slim'
gem 'rack', '1.3.3'
gem 'thor', :git => 'git://github.com/wycats/thor.git'

gem 'sqlite3'
gem 'pg'
gem 'mysql'

gem 'thin'
gem 'rake'
gem 'redcarpet'
