source 'http://rubygems.org'

gem 'seimtra', '0.0.1'
gem 'sinatra'
gem 'sequel'
gem 'slim'
gem 'rack', '1.3.3'

gem 'sqlite3', :group => [:development, :test]
gem 'pg', :group => :production

gem 'rake'
gem 'terminal-table'

